# Generated by Django 5.2 on 2025-04-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_name',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default='Tell the customer about your restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantownerprofile',
            name='restaurant_name',
            field=models.CharField(default='restaurant name', max_length=150),
        ),
    ]
