# Generated by Django 5.2 on 2025-04-21 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_restaurant_restaurant_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_owner_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurantownerprofile'),
        ),
        migrations.AlterField(
            model_name='restaurantownerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'restaurant'}, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
