# Generated by Django 5.2 on 2025-04-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_restaurant_owner_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantownerprofile',
            name='restaurant_name',
            field=models.CharField(max_length=150),
        ),
    ]
