# Generated by Django 5.2 on 2025-04-15 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username can contain only letters, digits, and spaces.', regex='^[A-Za-z0-9 ]+$')]),
        ),
    ]
