# Generated by Django 5.2 on 2025-04-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('restaurant', 'Restaurant Owner')], default='customer', max_length=20),
        ),
    ]
